name: prepare-semantic-release
description: Prepares the environment for semantic release
inputs:
  release-config-dir:
    description: The location of the release configuration
    required: true
  release-dir:
    description: The target dir, in which the release will be performed
    required: true
  node-version-file: 
    description: The location of the node version file
    required: false
    default: app/node-version
runs:
  using: composite
  steps:
    - id: setup-dependencies
      shell: bash
      run: sudo apt-get install -y moreutils
    - id: setup-release-rules
      shell: bash
      run: |
        {
          echo 'RELEASE_RULES<<EOF'
          echo '[
              { "breaking": true,       "release": "major" },
              { "type": "majorfeat",    "release": "major" },
              { "type": "feat",         "release": "minor" },
              { "type": "fix",          "release": "patch" },
              { "type": "refactor",     "release": "patch" },
              { "type": "perf",         "release": "patch" },
              { "type": "test",         "release": "patch" },
              { "type": "build",        "release": "patch" },
              { "type": "ci",           "release": "patch" },
              { "type": "chore",        "release": "patch" },
              { "type": "docs",         "release": "patch" },
              { "type": "no-release",   "release": false },
              { "type": "style",        "release": false }
          ]'
          echo EOF
        } >> "$GITHUB_ENV"
    - id: setup-force-release
      if: ${{ github.ref_name == 'dev' }}
      shell: bash
      run: |
        {
          echo 'RELEASE_RULES<<EOF'
          echo $RELEASE_RULES | jq -c '. += [{"message": "**", "release": "patch"}]'
          echo EOF
        } >> "$GITHUB_ENV"
    - id: setup-fs
      shell: bash
      run: |
        mkdir -p ${{ inputs.release-dir }}

        cp ${{ github.action_path }}/package.json \
          ${{ github.action_path }}/package-lock.json \
          ${{ inputs.release-dir }}/

        cat ${{ inputs.release-config-dir}}/releaserc.json |\
          jq '.branches = [
              "main",
              {
                  "name": "beta", "prerelease": true 
              }, {
                  "name": "dev", "channel": "nightly", "prerelease": "nightly"
              }
            ]' |\
          jq '.plugins += [[
            "@semantic-release/commit-analyzer",
            {
                "preset": "conventionalcommits",
                "releaseRules": ${{ env.RELEASE_RULES }}
            }
          ]]' |\
          sponge ${{ inputs.release-dir }}/.releaserc.json

        echo "Wrote:"
        cat ${{ inputs.release-dir }}/.releaserc.json
    - id: setup-node
      uses: actions/setup-node@v5
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: npm
        cache-dependency-path: ${{ inputs.release-dir }}
    - id: setup-npm
      shell: bash
      run: (cd ${{ inputs.release-dir }}; npm ci)