import {iCloudApp} from "../../src/app/icloud-app";
import {iCloud} from "../../src/lib/icloud/icloud";
import {PhotosLibrary} from "../../src/lib/photos-library/photos-library";

/**
 * Creates an iCloudApp object populated for testing
 * @param options - CLI options
 * @param photosLibrary - an initiated photosLibrary for handoff
 * @param icloud  - an initiated icloud object for handoff
 * @returns The iCloudApp object
 */
export function appWithOptions<T extends iCloudApp>(options: any, photosLibrary?: PhotosLibrary, icloud?: iCloud): T {
    const app = {
        options,
    };

    if (photosLibrary) {
        const photosLibraryVarName = `photosLibrary`;
        app[photosLibraryVarName] = photosLibrary;
    }

    if (icloud) {
        const icloudVarName = `icloud`;
        app[icloudVarName] = icloud;
    }

    return app as T;
}

export const rejectOptions = [
    {
        "options": [],
        "_desc": `No options`,
    }, {
        "options": [
            `/usr/bin/node`,
            `/home/icloud-photos-sync/main.js`,
            `--fail-on-mfa`,
            `-d`,
            `/opt/icloud-photos-library`,
            `-P`,
            `80`,
            `-l`,
            `info`,
            `--log-to-cli`,
            `-s`,
            `-t`,
            `5`,
            `-r`,
            `-1`,
            `--refresh-token`,
            `token`,
        ],
        "_desc": `Missing username & password`,
    }, {
        "options": [
            `/usr/bin/node`,
            `/home/icloud-photos-sync/main.js`,
            `-u`,
            `test@icloud.com`,
            `--fail-on-mfa`,
            `-d`,
            `/opt/icloud-photos-library`,
            `-P`,
            `80`,
            `-l`,
            `info`,
            `--log-to-cli`,
            `-s`,
            `-t`,
            `5`,
            `-r`,
            `-1`,
            `--refresh-token`,
            `token`,
        ],
        "_desc": `Missing password`,
    }, {
        "options": [
            `/usr/bin/node`,
            `/home/icloud-photos-sync/main.js`,
            `-u`,
            `test@icloud.com`,
            `-p`,
            `testPass`,
            `--fail-on-mfa`,
            `-d`,
            `/opt/icloud-photos-library`,
            `-P`,
            `eight`,
            `-l`,
            `info`,
            `--log-to-cli`,
            `-s`,
            `-t`,
            `5`,
            `-r`,
            `-1`,
            `--refresh-token`,
            `token`,
        ],
        "_desc": `Invalid port`,
    }, {
        "options": [
            `/usr/bin/node`,
            `/home/icloud-photos-sync/main.js`,
            `-u`,
            `test@icloud.com`,
            `-p`,
            `testPass`,
            `--fail-on-mfa`,
            `-d`,
            `/opt/icloud-photos-library`,
            `-P`,
            `80`,
            `-l`,
            `superInfo`,
            `--log-to-cli`,
            `-s`,
            `-t`,
            `5`,
            `-r`,
            `-1`,
            `--refresh-token`,
            `token`,
        ],
        "_desc": `Invalid log level`,
    }, {
        "options": [
            `/usr/bin/node`,
            `/home/icloud-photos-sync/main.js`,
            `-u`,
            `test@icloud.com`,
            `-p`,
            `testPass`,
            `--fail-on-mfa`,
            `-d`,
            `/opt/icloud-photos-library`,
            `-P`,
            `80`,
            `-l`,
            `info`,
            `--log-to-cli`,
            `-s`,
            `-t`,
            `five`,
            `-r`,
            `-1`,
            `--refresh-token`,
            `token`,
        ],
        "_desc": `Invalid download threads`,
    }, {
        "options": [
            `/usr/bin/node`,
            `/home/icloud-photos-sync/main.js`,
            `-u`,
            `test@icloud.com`,
            `-p`,
            `testPass`,
            `--fail-on-mfa`,
            `-d`,
            `/opt/icloud-photos-library`,
            `-P`,
            `80`,
            `-l`,
            `info`,
            `--log-to-cli`,
            `-s`,
            `-t`,
            `5`,
            `-r`,
            `inf`,
            `--refresh-token`,
            `token`,
        ],
        "_desc": `Invalid retries`,
    }, {
        "options": [
            `/usr/bin/node`,
            `/home/icloud-photos-sync/main.js`,
            `-u`,
            `test@icloud.com`,
            `-p`,
            `testPass`,
            `--fail-on-mfa`,
            `-d`,
            `/opt/icloud-photos-library`,
            `-P`,
            `80`,
            `-l`,
            `info`,
            `--log-to-cli`,
            `-s`,
            `-t`,
            `5`,
            `-r`,
            `inf`,
            `--refresh-token`,
        ],
        "_desc": `No command`,
    }, {
        "options": [
            `/usr/bin/node`,
            `/home/icloud-photos-sync/main.js`,
            `-u`,
            `test@icloud.com`,
            `-p`,
            `testPass`,
            `--fail-on-mfa`,
            `-d`,
            `/opt/icloud-photos-library`,
            `-P`,
            `80`,
            `-l`,
            `info`,
            `--log-to-cli`,
            `-s`,
            `-t`,
            `5`,
            `-r`,
            `inf`,
            `--refresh-token`,
            `dounicorn`,
        ],
        "_desc": `Invalid command`,
    }, {
        "options": [
            `/usr/bin/node`,
            `/home/icloud-photos-sync/main.js`,
            `-u`,
            `test@icloud.com`,
            `-p`,
            `testPass`,
            `--fail-on-mfa`,
            `-d`,
            `/opt/icloud-photos-library`,
            `-P`,
            `80`,
            `-l`,
            `info`,
            `--log-to-cli`,
            `-s`,
            `-t`,
            `5`,
            `-r`,
            `inf`,
            `--refresh-token`,
            `archive`,
        ],
        "_desc": `Missing archive path`,
    },
];

export const validOptions = {
    "token": [
        `/usr/bin/node`,
        `/home/icloud-photos-sync/main.js`,
        `-u`,
        `test@icloud.com`,
        `-p`,
        `testPass`,
        `--fail-on-mfa`,
        `-d`,
        `/opt/icloud-photos-library`,
        `-P`,
        `80`,
        `-l`,
        `info`,
        `--log-to-cli`,
        `-s`,
        `-t`,
        `5`,
        `-r`,
        `-1`,
        `--refresh-token`,
        `token`,
    ],
    "sync": [
        `/usr/bin/node`,
        `/home/icloud-photos-sync/main.js`,
        `-u`,
        `test@icloud.com`,
        `-p`,
        `testPass`,
        `--fail-on-mfa`,
        `-d`,
        `/opt/icloud-photos-library`,
        `-P`,
        `80`,
        `-l`,
        `info`,
        `--log-to-cli`,
        `-s`,
        `-t`,
        `5`,
        `-r`,
        `-1`,
        `--refresh-token`,
        `sync`,
    ],
    "archive": [
        `/usr/bin/node`,
        `/home/icloud-photos-sync/main.js`,
        `-u`,
        `test@icloud.com`,
        `-p`,
        `password`,
        `--fail-on-mfa`,
        `-d`,
        `/opt/icloud-photos-library`,
        `-P`,
        `80`,
        `-l`,
        `info`,
        `--log-to-cli`,
        `-s`,
        `-t`,
        `5`,
        `-r`,
        `-1`,
        `--refresh-token`,
        `--remote-delete`,
        `archive`,
        `/root/someTestDir/`,
    ],
};