#!/bin/bash

echo "'Resend MFA' helper linked"
BIN=$(docker run --entrypoint /usr/bin/which icloud-photos-sync:latest resend_mfa)
if [ $? -eq 1 ]; then
    echo " - Fail: $BIN"
    exit 1
fi
echo " - Pass: $BIN"

echo "'Resend MFA' helper executable"
TARGET=$(docker run --entrypoint /usr/bin/readlink icloud-photos-sync:latest -f ${BIN})
FILE_MODE=$(docker run --entrypoint /bin/stat icloud-photos-sync:latest -c %a ${TARGET})
if [ "$FILE_MODE" != "755" ]; then
    echo " - Fail: $FILE_MODE @ $TARGET"
    exit 1
fi
echo " - Pass: $FILE_MODE @ $TARGET"
exit 0