#!/bin/bash

source $(dirname $0)/_helper.sh

EXPECTED_CHECKSUM="e6b69510e98120fd656bdb1702192a7fa0a5e4b9"

###
###
echo "Full sync to $DIR"
###
###

runSync

# Checking if behaviour is as expected
for VALUE in \
    "local_albums_loaded=0i,local_assets_loaded=0i,remote_albums_fetched=8i,remote_assets_fetched=206i" \
    "assets_to_be_added=206i,assets_to_be_deleted=0i,assets_to_be_kept=0i" \
    "albums_to_be_added=8i,albums_to_be_deleted=0i,albums_to_be_kept=0i" \
    "SYNC_COMPLETED"
do
    assertMetric "$VALUE"
done
assertChecksum

###
###
echo "Delete 5 assets and perform re-sync"
###
###

# Remove files from library
for FILE in \
    "ali-kazal-6YyuNu1lCBE-unsplash.jpeg" \
    "andrea-de-santis-cRi_VYej6lE-unsplash.jpeg" \
    "2h-media-MOCpD78SHW0-unsplash.jpeg" \
    "2h-media-Q_x3Equ11Jk-unsplash.jpeg" \
    "aditya-vyas-pbY2DCN1Atk-unsplash-edited.jpeg"
do
    # Delete the files in the asset dir
    rm -f $(readlink -f "$DIR/.b971e88c-ca73-4712-9f70-202879ea8b26/$FILE")

    # Unlink them from their albums
    #   Memories/'2015 - 2016'
    #   Memories/2022/Spring_Autumn
    #   Memories/2022/'Winter sadness'
    #   Random
    for ALBUM in \
        "$DIR/.cc40a239-2beb-483e-acee-e897db1b818a/.fc649b1a-d22e-4b49-a5ee-066eb577d023" \
        "$DIR/.cc40a239-2beb-483e-acee-e897db1b818a/.6e7f4f44-445a-41ee-a87e-844a9109069d/.c8254e48-90f0-4f6d-8564-95a6718ee403" \
        "$DIR/.cc40a239-2beb-483e-acee-e897db1b818a/.6e7f4f44-445a-41ee-a87e-844a9109069d/.311f9778-1f40-4762-9e57-569ebf5fb070" \
        "$DIR/.b971e88c-ca73-4712-9f70-202879ea8b26"
    do
        unlink "$ALBUM/$FILE"
    done
done

runSync

# Checking if behaviour is as expected
for VALUE in \
    "local_albums_loaded=8i,local_assets_loaded=201i,remote_albums_fetched=8i,remote_assets_fetched=206i" \
    "assets_to_be_added=5i,assets_to_be_deleted=0i,assets_to_be_kept=201i" \
    "albums_to_be_added=5i,albums_to_be_deleted=5i,albums_to_be_kept=3i" \
    "SYNC_COMPLETED"
do
    assertMetric "$VALUE"
done
assertChecksum

# Cleaning up
rm -rf $DIR