name: test-api-token-setup
description: Sets up the environment for acquiring an API token for GH runners and connects to a wireguard peer, in order to enable MFA input
inputs:
  app-path:
    description: The path to the app directory
    required: false
    default: app
  wg-endpoint: 
    description: The endpoint (IP and port) of the wireguard peer
    required: true
  wg-peer-public-key:
    description: The wireguard peers's public key
    required: true
  wg-local-address:
    description: The IP address to assign to the runner
    required: true
  wg-remote-address:
    description: The IP address of the wireguard peer
    required: true
  wg-allowed-ips:
    description: The IPs to route through the wireguard tunnel
    required: true
  wg-private-key:
    description: The private key for the runner
    required: true
  wg-preshared-key:
    description: The preshared key
    required: true
runs:
  using: composite
  steps:
    - id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.app-path }}/node-version
        cache: npm
        cache-dependency-path: ${{ inputs.app-path }}
    - id: setup-npm
      shell: bash
      run: (cd ${{ inputs.app-path }}; npm ci)
    - id: build-app
      shell: bash
      run: (cd ${{ inputs.app-path }}; npm run build && npm run dist)
    - id: install-app
      shell: bash
      run: (cd ${{ inputs.app-path }}; npm link)
    - id: setup-wg
      shell: bash
      run: |
        sudo apt-get -y install wireguard

        echo "${{ inputs.wg-private-key }}" > private.key
        echo "${{ inputs.wg-preshared-key }}" > preshared.key

        sudo ip link add dev wg0 type wireguard
        sudo ip address add dev wg0 ${{ inputs.wg-local-address }} peer ${{ inputs.wg-remote-address }}
        sudo wg set wg0 \
          listen-port 48123 \
          private-key private.key \
          peer ${{ inputs.wg-peer-public-key }} \
          preshared-key preshared.key \
          endpoint ${{ inputs.wg-endpoint }} \
          persistent-keepalive 10 \
          allowed-ips ${{ inputs.wg-allowed-ips }}
    - id: start-wg
      shell: bash
      run: sudo ip link set up dev wg0